name: On Repository Dispatch
on:
  repository_dispatch:
    types: [argo_deploy]

jobs:
  print-payload:
    runs-on: ubuntu-latest
    steps:
      - name: Show payload
        run: |
          echo "Event type: ${{ github.event.action }}"
          echo "Payload:"
          echo '${{ toJson(github.event.client_payload) }}'